version: '3.7'

services:
  debian-xfce:
    image: "local/debian-xfce-vnc"
    build:
      context: ".."
      dockerfile: "Dockerfile"
    ports:
      - 127.0.99.13:5902:5901
      - 127.0.99.13:6902:6901
